### PR TITLE
chore(uptime): add carbon-platform

### PR DESCRIPTION
**Pull request by alisonjoseph**

### CODE REVIEW

**Review by jdharvey-ibm — CHANGES_REQUESTED** [review]
Hmm, I think there should only be one file changed to support this. Just the `.upptimerc.yml` file.

**Comment by alisonjoseph** [comment]
@jdharvey-ibm that's the only file I changed, not sure if the other changes were automated? 🤔

**Comment by joshblack** [comment]
Super weird with the commits 🤔 Put up: https://github.com/carbon-design-system/uptime/pull/24 real quick to see if it happens there too

**Review by joshblack — APPROVED** [review]

**Review by jdharvey-ibm — APPROVED** [review]
super weird, haha. well as long as it works!

**Comment by alisonjoseph** [comment]
Wait, do we want to merge this, if its just going to come back with a 404 for our login page @jdharvey-ibm ?

**Comment by jdharvey-ibm** [comment]
@alisonjoseph good point! I looked through their docs to see if it said anything about 400 vs 200 responses and if that triggers the down notification, but I didn't find anything. None of our API routes are protected by the auth middleware, so we could add an API route called `readiness` that just returns a 204 and put the route to that in the config here instead. Kubernetes likes to have two health check endpoints: one called `liveness` and one called `readiness`, so adding one (or both) in the nextjs app would definitely benefit our eventual switch to k8s as well.
Those both get auto-added to all of our microservices that are based on Nest: https://github.com/carbon-design-system/carbon-platform/blob/main/packages/api/src/main/microservice/status-endpoint/status.controller.ts

**Comment by alisonjoseph** [comment]
Going to close this for now and update the issue in our repo.

**Pull request closed without merging**
